// ═══════════════════════════════════════════════════════════
// ECOFUNDRIVE V2.0 - TEST IMAGE GENERATION SCRIPT
// Generate 3 images for Club 55 (test keyword)
// ═══════════════════════════════════════════════════════════

import 'dotenv/config';
import { generatePageContent } from '../src/lib/claude';
import { generatePageImages } from '../src/lib/fluxpro';

// Test keyword: Club 55
const testKeyword = {
  keyword: "club-55-saint-tropez",
  location: "Club 55, Saint-Tropez",
  language: "fr",
  category: "restaurants",
  url: "/fr/club-55-saint-tropez",
  authority: true,
  mode: "A" as const,
  wordcount: 2400,
  meta_title: "Club 55 Saint-Tropez | VTC Tesla Côte d'Azur - ECOFUNDRIVE",
  meta_description: "Transfert VTC Tesla vers Club 55 Saint-Tropez. Service premium pour vos déjeuners à Pampelonne. Réservation 24/7."
};

async function generateTestImages() {
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('🎨 TEST IMAGE GENERATION - CLUB 55 SAINT-TROPEZ');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  try {
    // Step 1: Generate content with Claude (to get image prompts)
    console.log('📝 Step 1: Generating content with Claude...\n');
    const pageContent = await generatePageContent(testKeyword);

    if (!pageContent.image_prompts) {
      throw new Error('❌ No image prompts generated by Claude!');
    }

    console.log('✅ Content generated successfully!\n');
    console.log('📋 Image prompts received:');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`\n🎬 HERO: ${pageContent.image_prompts.hero}\n`);
    console.log(`🎬 MID: ${pageContent.image_prompts.mid}\n`);
    console.log(`🎬 END: ${pageContent.image_prompts.end}\n`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    // Step 2: Generate 3 images with Flux Pro
    console.log('📝 Step 2: Generating 3 images with Flux Pro...\n');
    const imageResults = await generatePageImages(
      testKeyword.keyword,
      pageContent.image_prompts
    );

    // Step 3: Display results
    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('📊 RESULTS SUMMARY');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    console.log(`Hero Image: ${imageResults.hero.success ? '✅ SUCCESS' : '❌ FAILED'}`);
    if (imageResults.hero.success) {
      console.log(`   Path: ${imageResults.hero.url}`);
    } else {
      console.log(`   Error: ${imageResults.hero.error}`);
    }

    console.log(`\nMid Image: ${imageResults.mid.success ? '✅ SUCCESS' : '❌ FAILED'}`);
    if (imageResults.mid.success) {
      console.log(`   Path: ${imageResults.mid.url}`);
    } else {
      console.log(`   Error: ${imageResults.mid.error}`);
    }

    console.log(`\nEnd Image: ${imageResults.end.success ? '✅ SUCCESS' : '❌ FAILED'}`);
    if (imageResults.end.success) {
      console.log(`   Path: ${imageResults.end.url}`);
    } else {
      console.log(`   Error: ${imageResults.end.error}`);
    }

    const successCount = [imageResults.hero, imageResults.mid, imageResults.end]
      .filter(r => r.success).length;

    console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    console.log(`🎉 TOTAL: ${successCount}/3 images generated successfully`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    if (successCount === 3) {
      console.log('✅ All images generated! You can now test the build:\n');
      console.log('   npm run build\n');
      console.log('   npx serve dist\n');
      console.log('Then open: http://localhost:3000/fr/club-55-saint-tropez\n');
    } else {
      console.log('⚠️ Some images failed. Check errors above.\n');
    }

  } catch (error: any) {
    console.error('\n❌ ERROR:', error.message);
    console.error(error);
    process.exit(1);
  }
}

// Run script
generateTestImages();
